-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 21:39:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema billsify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema billsify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `billsify` DEFAULT CHARACTER SET utf8 ;
USE `billsify` ;

-- -----------------------------------------------------
-- Table `billsify`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `billsify`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `billsify`.`ususario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `billsify`.`ususario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`, `rol_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_ususario_rol1_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_ususario_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `billsify`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `billsify`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `billsify`.`noticia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `cuerpo` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `billsify`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `billsify`.`proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `tech_stack` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `tiempo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `billsify`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `billsify`.`cita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NULL,
  `comentarios` VARCHAR(45) NULL,
  `ususario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ususario_id`),
  INDEX `fk_cita_ususario_idx` (`ususario_id` ASC) VISIBLE,
  CONSTRAINT `fk_cita_ususario`
    FOREIGN KEY (`ususario_id`)
    REFERENCES `billsify`.`ususario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
